### ISSUE TITLE
Rename params with incoherent names

### ISSUE THREAD

**Issue by olbapjose** [mjuez/approx-smote#2]
Hi again,

It would be easier for a Pyspark wrapper to have all params with identical names to the correponding private member variables of the class. E.g.

https://github.com/mjuez/approx-smote/blob/4672945a5cd244b54038b857e09db30f330604ba/src/main/scala/org/apache/spark/ml/instance/ASMOTE.scala#L265

https://github.com/mjuez/approx-smote/blob/4672945a5cd244b54038b857e09db30f330604ba/src/main/scala/org/apache/spark/ml/instance/ASMOTE.scala#L291

Looks like you are deciding on the proper name :-)  it would be desirable to have the exact same name in the param name as in the variable name. It happens with maxDistance/maxNeighbors, and bufferSizeSampleSizes/bufferSizeSampleSize. I would appreciate it if you can please update them so my Pyspark wrapper code can properly mirror yours. In the meantime I have a temporary fix.

Thanks!

**Comment by mjuez** [comment]
Probably when I was thinking about what variable and param names fit best with the functionality, I forgot to check them and put everything in a coherent way.

Following your comments, I renamed everything to make it consistent. Thank you!
