### ISSUE TITLE
Input should not assume the only columns are the label and features

### ISSUE THREAD

**Issue by olbapjose** [mjuez/approx-smote#3]
Hi Mario,

When including the ASMOTE in a pipeline, I'm getting an exception here:

https://github.com/mjuez/approx-smote/blob/4672945a5cd244b54038b857e09db30f330604ba/src/main/scala/org/apache/spark/ml/instance/ASMOTE.scala#L154

It looks like `transform()` expects that the only columns present in the data are the labelCol and the featuresCol. However, I think this constraint is not realistic (and not difficult to remove). As you know, in order to construct a vectorized featuresCol, we usually create a VectorAssembler as a part of a bigger pipeline, where ASMOTE will be included as well, just as another stage. 

Unfortunately, this does not work properly as it is actually weird to require a stage that removes all the other columns. Notice we normally include the VectorAssembler after previous steps, and normally no "remove-columns" step is used in pipelines.

Thanks!

**Comment by mjuez** [comment]
This issue was closely related to #1, so I tried to fix everything. I hope everything works as it should from now on.

Thank you for your useful comments.
